version: '3'

services:
  node_server:
    build: ./Node_server
    container_name: node_server
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - ./Node_server:/usr/src/app
    ports:
      - '30001:30001'
    depends_on:
      - mongo
    networks:
      - app-network
    command: 'yarn start'

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
    volumes:
      - ./Node_server/user_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
